In [41]:
# Import Required Library
import pandas as pd
import numpy as np


import matplotlib.pyplot as plt
plt.style.use('ggplot')
%matplotlib inline  

from sklearn import linear_model
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import PolynomialFeatures

from sklearn import model_selection #import cross_val_score, StratifiedKFold
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier, export_graphviz
from sklearn import metrics  # mean_squared_error, mean_absolute_error, median_absolute_error, explained_variance_score, r2_score
from sklearn.feature_selection import SelectFromModel, RFECV
from sklearn.externals import joblib

import pickle

In [42]:
# load training data 
df_train = pd.read_csv('Dataset/train4.csv')
df_train.head()

,id,cycle,setting1,setting2,setting3,s1,s2,s3,s4,s5,...,s13,s14,s15,s16,s17,s18,s19,s20,s21,RUL
0,1,1,42.0049,0.8400,100.0,445.00,549.68,1343.43,1112.93,3.91,...,2387.99,8074.83,9.3335,0.02,330,2212,100.00,10.62,6.3670,320
1,1,2,20.0020,0.7002,100.0,491.19,606.07,1477.61,1237.50,9.35,...,2387.73,8046.13,9.1913,0.02,361,2324,100.00,24.37,14.6552,319
2,1,3,42.0038,0.8409,100.0,445.00,548.95,1343.12,1117.05,3.91,...,2387.97,8066.62,9.4007,0.02,329,2212,100.00,10.48,6.4213,318
3,1,4,42.0000,0.8400,100.0,445.00,548.70,1341.24,1118.03,3.91,...,2388.02,8076.05,9.3369,0.02,328,2212,100.00,10.54,6.4176,317
4,1,5,25.0063,0.6207,60.0,462.54,536.10,1255.23,1033.59,7.05,...,2028.08,7865.80,10.8366,0.02,305,1915,84.93,14.03,8.6754,316

In [43]:
# load test data
df_test = pd.read_csv('Dataset/test4.csv')
df_test.head()

,id,cycle,setting1,setting2,setting3,s1,s2,s3,s4,s5,...,s13,s14,s15,s16,s17,s18,s19,s20,s21,RUL
0,1,230,25.0070,0.6214,60.0,462.54,537.66,1264.31,1046.41,7.05,...,2028.53,7890.31,10.7615,0.02,308,1915,84.93,14.41,8.6329,22
1,2,153,41.9989,0.8400,100.0,445.00,549.96,1354.05,1133.55,3.91,...,2387.72,8073.44,9.3925,0.02,331,2212,100.00,10.58,6.4325,39
2,3,141,42.0005,0.8401,100.0,445.00,549.47,1341.06,1118.90,3.91,...,2388.18,8095.58,9.2974,0.02,330,2212,100.00,10.61,6.3488,107
3,4,208,25.0018,0.6207,60.0,462.54,536.06,1253.49,1038.53,7.05,...,2028.30,7878.63,10.8396,0.02,306,1915,84.93,14.41,8.5696,75
4,5,51,25.0039,0.6200,60.0,462.54,537.36,1263.60,1052.52,7.05,...,2028.24,7873.75,10.9094,0.02,307,1915,84.93,14.19,8.6248,149

In [44]:
features_orig = ['setting1','setting2','setting3','s1','s2','s3','s4','s5','s6','s7','s8','s9','s10','s11','s12','s13','s14','s15','s16','s17','s18','s19','s20','s21']

features = features_orig


X_train = df_train[features]
y_train = df_train['RUL']

X_test = df_test[features]
y_test = df_test['RUL']

# Linear Regression

In [45]:
#try linear regression

linreg = linear_model.LinearRegression()
linreg.fit(X_train, y_train)

y_test_predict = linreg.predict(X_test)
y_train_predict = linreg.predict(X_train)

print('R^2 training: %.3f, R^2 test: %.3f' % (
      (metrics.r2_score(y_train, y_train_predict)), 
      (metrics.r2_score(y_test, y_test_predict))))


print("Root Mean Squared Error : " + (metrics.mean_squared_error(y_test, y_test_predict)**0.5).astype(str) )
print("Meat Absolute Error : " + (metrics.mean_absolute_error(y_test, y_test_predict).astype(str) ))
print("R^2 : " + (metrics.r2_score(y_test, y_test_predict).astype(str) ))
print("Explained Variance : " + (metrics.explained_variance_score(y_test, y_test_predict).astype(str) ))

# Output a pickle file for the model
#joblib.dump(linreg, 'linreg_model.pkl') 

# Test Prediction
# model = joblib.load(open('linreg_model.pkl','rb'))
# print(model.predict([[2,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]]))

R^2 training: 0.549, R^2 test: 0.233
Root Mean Squared Error : 47.75764832870831
Meat Absolute Error : 38.731711248625466
R^2 : 0.2327909053988092
Explained Variance : 0.4758950208377618

# Polynomial Regression

In [46]:
#try Polynomial regression

poly = PolynomialFeatures(degree=2)

X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.fit_transform(X_test)


polyreg = linear_model.LinearRegression()
polyreg.fit(X_train_poly, y_train)

y_test_predict = polyreg.predict(X_test_poly)
y_train_predict = polyreg.predict(X_train_poly)

print('R^2 training: %.3f, R^2 test: %.3f' % (
      (metrics.r2_score(y_train, y_train_predict)), 
      (metrics.r2_score(y_test, y_test_predict))))

print("Root Mean Squared Error : " + (metrics.mean_squared_error(y_test, y_test_predict)**0.5).astype(str) )
print("Meat Absolute Error : " + (metrics.mean_absolute_error(y_test, y_test_predict).astype(str) ))
print("R^2 : " + (metrics.r2_score(y_test, y_test_predict).astype(str) ))
print("Explained Variance : " + (metrics.explained_variance_score(y_test, y_test_predict).astype(str) ))

# Output a pickle file for the model
#joblib.dump(rf, 'FD004.pkl')

R^2 training: 0.609, R^2 test: 0.336
Root Mean Squared Error : 44.41684563450936
Meat Absolute Error : 33.56273423279485
R^2 : 0.3363741391755054
Explained Variance : 0.4697145877018216

# Random Forest

In [47]:
#try Random Forest

rf = RandomForestRegressor(n_estimators=100, max_features=3, max_depth=4, n_jobs=-1, random_state=1) 

rf.fit(X_train, y_train)

y_test_predict = rf.predict(X_test)
y_train_predict = rf.predict(X_train)

print('R^2 training: %.3f, R^2 test: %.3f' % (
      (metrics.r2_score(y_train, y_train_predict)), 
      (metrics.r2_score(y_test, y_test_predict))))

print("Root Mean Squared Error : " + (metrics.mean_squared_error(y_test, y_test_predict)**0.5).astype(str) )
print("Meat Absolute Error : " + (metrics.mean_absolute_error(y_test, y_test_predict).astype(str) ))
print("R^2 : " + (metrics.r2_score(y_test, y_test_predict).astype(str) ))
print("Explained Variance : " + (metrics.explained_variance_score(y_test, y_test_predict).astype(str) ))

# Output a pickle file for the model
# joblib.dump(rf, 'FD003.pkl')

R^2 training: 0.380, R^2 test: 0.030
Root Mean Squared Error : 53.688558324878294
Meat Absolute Error : 46.019333946757854
R^2 : 0.030402782856466692
Explained Variance : 0.5226009375938043

# Decision Tree

In [48]:
#try Decision Tree

dtrg = DecisionTreeRegressor(max_depth=7, random_state=123)
dtrg.fit(X_train, y_train)

y_test_predict = dtrg.predict(X_test)
y_train_predict = dtrg.predict(X_train)

print('R^2 training: %.3f, R^2 test: %.3f' % (
      (metrics.r2_score(y_train, y_train_predict)), 
      (metrics.r2_score(y_test, y_test_predict))))

print("Root Mean Squared Error : " + (metrics.mean_squared_error(y_test, y_test_predict)**0.5).astype(str) )
print("Meat Absolute Error : " + (metrics.mean_absolute_error(y_test, y_test_predict).astype(str) ))
print("R^2 : " + (metrics.r2_score(y_test, y_test_predict).astype(str) ))
print("Explained Variance : " + (metrics.explained_variance_score(y_test, y_test_predict).astype(str) ))

R^2 training: 0.541, R^2 test: 0.287
Root Mean Squared Error : 46.02555707545571
Meat Absolute Error : 34.096460492418096
R^2 : 0.287432544294003
Explained Variance : 0.4640394913938929